# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = 'ubuntu/jammy64'
AGENT_IMAGE = 'fedora/37-cloud-base'
NODE_COUNT = 1

Vagrant.configure("2") do |config|

  config.vm.define "main" do |ciConfig|
    ciConfig.vm.box = BOX_IMAGE
    ciConfig.ssh.insert_key = false
    ciConfig.vm.hostname = 'dev-ci'
    ciConfig.vm.provider :virtualbox do |vb|
      ciConfig.vm.network :private_network, ip: "192.168.56.10"
      vb.gui = false
      vb.memory = "1024"
      vb.cpus = "1"
    end
    ciConfig.vm.network "forwarded_port", guest: 8080, host: 8080
    ciConfig.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y htop git openjdk-11-jdk-headless
    SHELL
    ciConfig.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always"
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "agent-#{i}" do |agentConfig|
      agentConfig.vm.box = AGENT_IMAGE
      agentConfig.vm.hostname = "agent-#{i}"
      agentConfig.vm.network :private_network, ip: "192.168.56.#{i + 10}"
      agentConfig.vm.synced_folder ".", "/vagrant"
      agentConfig.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.memory = "1024"
        vb.cpus = "1"
      end
      agentConfig.vm.provision "shell", inline: <<-SHELL
        dnf update -y
        dnf install -y htop git java-11-openjdk-headless java-11-openjdk-devel
        # su - jenkins -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
        # su - jenkins -c "nvm install --lts"
        
        useradd -m -G wheel -s /bin/bash jenkins
        # echo -e "jenkins\njenkins" | passwd jenkins
        mkdir -p /home/jenkins/.ssh
        chmod 700 /home/jenkins/.ssh
        cat /vagrant/ci-key-ed25519 > "/home/jenkins/.ssh/authorized_keys"
        chown -R jenkins:jenkins /home/jenkins/.ssh
        chmod 600 /home/jenkins/.ssh/authorized_keys
      SHELL
    end
  end

  config.vm.provision :docker
  # config.vm.provision "shell", path: "provision-users.sh"
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = true
    ansible.galaxy_roles_path = "ansible/roles"
  end
end
