# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/amazonlinux-2'
  #   config.vm.network 'private_network', ip: '10.10.0.121'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
  end
  config.vm.provision :shell, inline: <<-SCRIPT
    yum update -y
  SCRIPT
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
    ansible.verbose = true
    
  end
end
