# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9"

  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "256"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # dnf update -y
    dnf install -y nc
    useradd -m -G users,wheel -s /bin/bash test
    mkdir -p /home/test/.ssh
    cat /vagrant/test-ed25519.pub > /home/test/.ssh/authorized_keys
    chmod 700 /home/test/.ssh
    chmod 600 /home/test/.ssh/authorized_keys
    chown -R test.test /home/test
  SHELL
end
