---
- name: Provision VMs
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/users.yml
    - vars/default.yml

  # pre_tasks:
  #   - name: Update packages db
  #     apt:
  #       name: python3-pip
  #       update_cache: yes
      
  roles:
    # - { role: common/utils, tags: ["utils"] }
    - { role: common/users, tags: ["users"] }

  tasks: []
